docs:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md']
ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/workflows/**']
content:
  - changed-files:
      - any-glob-to-any-file: ['content/**']
