name: "common-setup"
description: "Cache & install shared deps (npm/pip/apt)"
inputs:
  npm:  { default: "false" }
  pip:  { default: "false" }
  apt:  { default: "false" }
runs:
  using: "composite"
  steps:
    - name: Cache pip
      if: ${{ inputs.pip == 'true' }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: pip install
      if: ${{ inputs.pip == 'true' }}
      shell: bash
      run: |
        python -m pip install -U pip
        [ -f requirements.txt ] && pip install -r requirements.txt || true

    - name: Cache npm
      if: ${{ inputs.npm == 'true' }}
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json','**/package.json') }}
        restore-keys: ${{ runner.os }}-npm-
    - name: npm global tools
      if: ${{ inputs.npm == 'true' }}
      shell: bash
      run: |
        npm i -g @marp-team/marp-cli || true

    - name: Cache apt
      if: ${{ inputs.apt == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt
          /var/lib/apt/lists
        key: ${{ runner.os }}-apt-v1-${{ hashFiles('.github/apt-packages.txt') }}
        restore-keys: ${{ runner.os }}-apt-v1-
    - name: apt install
      if: ${{ inputs.apt == 'true' }}
      shell: bash
      run: |
        sudo apt-get update
        [ -f .github/apt-packages.txt ] && xargs -a .github/apt-packages.txt sudo apt-get install -y || true
