name: agent-poc
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const n = context.payload.issue.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner, repo: context.repo.repo, issue_number: n,
              body: `受理: ${new Date().toISOString()}（agent-poc）`
            });
