name: go_kill
on:
  issue_comment:
    types: [created]
permissions:
  pull-requests: write
  contents: write
jobs:
  handle:
    if: github.event.issue.pull_request != null &&
        (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER') &&
        (contains(github.event.comment.body, '/go') || contains(github.event.comment.body, '/kill'))
    runs-on: ubuntu-latest
    steps:
      - name: Go or kill
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if echo "${{ github.event.comment.body }}" | grep -q '/go'; then
            gh pr ready ${{ github.event.issue.number }} -R $GITHUB_REPOSITORY
          fi
          if echo "${{ github.event.comment.body }}" | grep -q '/kill'; then
            gh pr close ${{ github.event.issue.number }} -R $GITHUB_REPOSITORY --delete-branch
          fi
