name: labeler
on:
  pull_request:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened, edited]
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  apply-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
