name: site
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  build:
    if: >
      github.event.issue.pull_request != null &&
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') &&
      startsWith(github.event.comment.body, '/site')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Resolve PR and content dir
        id: ctx
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.issue.number;
            const arg = (context.payload.comment.body || "").replace(/^\/site\s*/,'').trim();
            core.setOutput('pr', String(prNumber));
            core.setOutput('branch', context.payload.issue.pull_request.head.ref);
            core.setOutput('content', arg || 'content');

      - run: |
          git fetch origin "${{ steps.ctx.outputs.branch }}"
          git checkout "${{ steps.ctx.outputs.branch }}"

      - name: Ensure minimal content
        run: |
          mkdir -p content
          if [ ! -f "content/hello.md" ]; then
            echo "# Hello" > content/hello.md
            echo "" >> content/hello.md
            echo "最小サンプルです。" >> content/hello.md
          fi

      - name: Build simple static site
        run: |
          python -m pip install -U pip
          python -m pip install -U mkdocs mkdocs-material
          echo "site_name: Repo Site" > mkdocs.yml
          echo "nav:" >> mkdocs.yml
          find "${{ steps.ctx.outputs.content }}" -name "*.md" -maxdepth 2 | sed 's|.*/||;s|.md$||' | awk '{print "  - "$0": '${{ steps.ctx.outputs.content }}/"$0".md"}' >> mkdocs.yml
          mkdocs build -d public_site

      - name: Commit to docs/site
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          mkdir -p docs/site
          rsync -a --delete public_site/ docs/site/
          git add docs/site
          if git diff --cached --quiet; then
            echo "No site changes."
          else
            git commit -m "site: build docs/site from ${{ steps.ctx.outputs.content }}"
            git push origin "${{ steps.ctx.outputs.branch }}"
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: site-pr-${{ steps.ctx.outputs.pr }}
          path: public_site
          retention-days: 7
