name: site
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
jobs:
  build:
    if: >
      github.event.issue.pull_request != null &&
      (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER') &&
      contains(github.event.comment.body, '/site')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.issue.pull_request.head.repo.full_name }}
          ref: ${{ github.event.issue.pull_request.head.ref }}
      - run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Build site
        run: |
          mkdir -p docs/site
          for f in content/*.md; do
            b=$(basename "$f" .md)
            pandoc "$f" -o "docs/site/$b.html"
          done
      - name: Commit site
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/site
          git commit -m "chore: update site" || echo "no changes"
          git push
