name: thumb
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  build:
    if: >
      github.event.issue.pull_request != null &&
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') &&
      startsWith(github.event.comment.body, '/thumb')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Resolve PR and target
        id: ctx
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.issue.number;
            const arg = (context.payload.comment.body || "").replace(/^\/thumb\s*/,'').trim() || 'content/hello.md';
            core.setOutput('pr', String(pr));
            core.setOutput('branch', context.payload.issue.pull_request.head.ref);
            core.setOutput('target', arg);

      - run: |
          git fetch origin "${{ steps.ctx.outputs.branch }}"
          git checkout "${{ steps.ctx.outputs.branch }}"

      - name: Install ImageMagick & fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick fonts-noto-cjk

      - name: Derive title
        id: title
        run: |
          set -e
          T="${{ steps.ctx.outputs.target }}"
          if [ -f "$T" ]; then
            TITLE=$(grep -m1 -E '^(#|title:)' "$T" | sed -E 's/^#\s*|^title:\s*//')
            [ -z "$TITLE" ] && TITLE=$(basename "$T" .md)
          else
            TITLE=$(basename "$T")
          fi
          echo "value=$TITLE" >> $GITHUB_OUTPUT

      - name: Render thumbnails
        run: |
          set -e
          slug=$(basename "${{ steps.ctx.outputs.target }}" | sed -E 's/\.[^.]+$//')
          mkdir -p public/og public/thumb
          convert -size 1200x630 xc:white -gravity center -pointsize 64 -annotate 0 "${{ steps.title.outputs.value }}" "public/og/$slug.png"
          for s in 256 512 1024; do
            convert "public/og/$slug.png" -resize ${s}x${s} "public/thumb/$slug-$s.webp"
          done

      - name: Commit images
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git add public/og public/thumb
          if git diff --cached --quiet; then
            echo "No image changes."
          else
            git commit -m "thumb: generate OG/thumb for ${{ steps.ctx.outputs.target }}"
            git push origin "${{ steps.ctx.outputs.branch }}"
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: thumb-pr-${{ steps.ctx.outputs.pr }}
          path: |
            public/og/*.png
            public/thumb/*.webp
